# Generated by Django 3.2 on 2021-05-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=30)),
                ('subtotal', models.CharField(max_length=30)),
                ('total', models.CharField(max_length=30)),
                ('descuento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='usuarioadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='usuariooperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=30)),
            ],
        ),
    ]
